### ISSUE TITLE
Need to fix

### ISSUE THREAD

**Issue by managedcoder** [managedcoder/JumpStreetMobile#2]
Need to fix the following bug in Sayed's JumpStreetVS fork that happens on File | New Project Jump Street
![bug](https://cloud.githubusercontent.com/assets/17769186/14032011/61c003ca-f1e6-11e5-89e7-3215defd19d5.png)

**Comment by sayedihashimi** [comment]
Thanks, I will take a look. Can you add me to this repo, that way issues can be assigned to me?

**Comment by managedcoder** [comment]
Ok, I added you

**Comment by sayedihashimi** [comment]
Try the vsix at https://ci.appveyor.com/project/sayedihashimi/jumpstreetmobile/build/artifacts

**Comment by managedcoder** [comment]
Ok, that .visx does generate a Jump Street app successfully but references to Xamarin library references in the iOS, Win 8, and Win Phone 8 project are broken for some reason (see screen shots to see which ones are messed up).  The Android and Service project are fine.  Not sure what is going on there.

[cid:image001.png@01D187C4.DFA4E300]


[cid:image002.png@01D187C4.DFA4E300]


[cid:image003.png@01D187C4.DFA4E300]

**Comment by sayedihashimi** [comment]
Screen shots in emails don't show up in GitHub. You have to reply at GitHub.com to add images.

**Comment by managedcoder** [comment]
Good news!  That .vsix is fine!  Turns out I ran out of disk space again while building the solution and that caused the strangeness in those projects.  I freed up disk space and it built and ran just fine.

-russ

**Comment by sayedihashimi** [comment]
Ok ,so looks like we are good here. Go ahead and close this issue. Also can you post a new issue with the needed replacements as we discussed the other day?
